#!/usr/bin/env bash
set -euo pipefail

OWNER="${1:-}"
REPO="${2:-}"
BRANCH="${3:-}"
SKINS_DIR="${4:-skins}"
OUTPUT_FILE="${5:-skins.md}"

if [[ -z "$OWNER" || -z "$REPO" || -z "$BRANCH" ]]; then
  echo "Usage: $0 OWNER REPO BRANCH [SKINS_DIR] [OUTPUT_FILE]" >&2
  exit 1
fi

if [ -d "$SKINS_DIR" ]; then
  # Collect only direct children with .osk or .zip (case-insensitive)
  mapfile -t FILES < <(
    find "$SKINS_DIR" -maxdepth 1 -mindepth 1 -type f \
      \( -iname "*.osk" -o -iname "*.zip" \) -printf "%f\n"
  )
else
  FILES=()
fi

# If no files, still regenerate skins.md to keep things deterministic
urlencode() {
  python - "$1" << 'PY'
import sys, urllib.parse
s = sys.argv[1]
print(urllib.parse.quote(s))
PY
}

to_skin_name() {
  python - "$1" << 'PY'
import sys, re, os
filename = sys.argv[1]
name, ext = os.path.splitext(filename)
name = name.replace('_', ' ')
name = name.replace('.', ' ')
name = re.sub(r'\s+', ' ', name).strip()

def title_word(word: str) -> str:
    if not word:
        return word
    if word[0] in '[({':
        if len(word) > 1 and word[1].isalpha():
            return word[0] + word[1].upper() + word[2:]
        return word
    for i, ch in enumerate(word):
        if ch.isalpha():
            return word[:i] + ch.upper() + word[i+1:]
    return word

parts = name.split(' ')
titled_parts = [title_word(p) for p in parts]
result = ' '.join(titled_parts)
print(result)
PY
}

# Sort files case-insensitively with case-sensitive tiebreaker
readarray -t SORTED_FILES < <(
  printf '%s\n' "${FILES[@]}" \
  | python - << 'PY'
import sys
files = [line.strip() for line in sys.stdin if line.strip()]
files.sort(key=lambda s: (s.lower(), s))
for f in files:
    print(f)
PY
)

{
  echo "# osu! skinhub-basic skins index"
  echo
  echo "> This file is auto-generated by .github/workflows/generate-skins-index.yml. Do not edit manually."
  echo
  echo "This index lists all osu! skins stored as .osk or .zip archives directly under the skins/ directory, with direct GitHub download links that work for this repository and its forks."
  echo
  echo "| Skin | Filename | Download |"
  echo "| --- | --- | --- |"

  for f in "${SORTED_FILES[@]}"; do
    [ -n "$f" ] || continue
    skin_name="$(to_skin_name "$f")"
    encoded="$(urlencode "$f")"
    # Always use the current repo (OWNER/REPO) and current ref (BRANCH) from the workflow context,
    # so forks generate correct, fork-local links.
    download_url="https://github.com/${OWNER}/${REPO}/raw/${BRANCH}/skins/${encoded}"
    echo "| ${skin_name} | ${f} | [Download](${download_url}) |"
  done
} > "$OUTPUT_FILE"